### ISSUE TITLE
Composer installation

### ISSUE THREAD

**Issue by sc0ttkclark** [eventbrite/eventbrite-sdk-php#14]
Can you add composer installation instructions?

**Comment by YBthebest** [comment]
For composer installation:
`    "repositories": {
        "eventbrite-sdk-php": {
            "type": "vcs",
            "url": "https://github.com/eventbrite/eventbrite-sdk-php"
        }
    }`

and in your require block:
`"eventbrite/eventbrite-sdk-php": "dev-master"`

**Comment by sc0ttkclark** [comment]
Thanks!
